# Generated by Django 4.0.6 on 2022-08-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='carts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemid', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('username', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='items',
            fields=[
                ('itemid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('descr', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='itemsimg')),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('orderid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('primary_phone_no', models.CharField(max_length=50)),
                ('secondary_phone_no', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=50)),
                ('total_price', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='books',
            name='user',
        ),
    ]
