# Generated by Django 4.0.6 on 2022-08-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_carts_items_orders_remove_books_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='descr',
            field=models.CharField(max_length=1000),
        ),
    ]
