# Generated by Django 4.0.6 on 2022-09-02 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_items_descr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='email',
        ),
        migrations.RemoveField(
            model_name='books',
            name='venue',
        ),
        migrations.AlterField(
            model_name='books',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
